//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Project.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Restaurant_DbEntities1 : DbContext
    {
        public Restaurant_DbEntities1()
            : base("name=Restaurant_DbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Giris> Tbl_Giris { get; set; }
        public virtual DbSet<Tbl_Hakkimda> Tbl_Hakkimda { get; set; }
        public virtual DbSet<Tbl_Menu_Yemekler> Tbl_Menu_Yemekler { get; set; }
        public virtual DbSet<Tbl_NedenSecmelisiniz> Tbl_NedenSecmelisiniz { get; set; }
        public virtual DbSet<Tbl_Onerilerimiz> Tbl_Onerilerimiz { get; set; }
        public virtual DbSet<Tbl_Resimler> Tbl_Resimler { get; set; }
        public virtual DbSet<Tbl_Rezervasyon> Tbl_Rezervasyon { get; set; }
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
    }
}
