//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Rezervasyon
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Tarih { get; set; }
        public string Saat { get; set; }
        public Nullable<byte> Kisi_Sayisi { get; set; }
        public string Aciklama { get; set; }
    }
}
