//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant_Project.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Yorumlar
    {
        public int ID { get; set; }
        public string AdSoyad { get; set; }
        public string Meslek { get; set; }
        public string Yorum { get; set; }
        public string Resim_Adres { get; set; }
    }
}
